version: "3"

services:
  flaskweb:
    build:
      context: .
      dockerfile: Dockerfile
    image: lrusinou/flaskapp
    environment:
      - "FLASK_ENV=development"
    ports:
      - "5000:5000"

  redis:
    image: redis:4.0.11-alpine
